// Andmebaasi skeem diagrammi jaoks (allikas: docs/database/2_create.sql).
// Skeemi muutmisel tuleb ka see fail käsitsi uuendada.
// group määrab, millisesse diagrammi veergu tabel paigutatakse.

export const SCHEMA_GROUPS = [
  { index: 0, label: 'Kasutajad ja grupid' },
  { index: 1, label: 'Kompetentsid' },
  { index: 2, label: 'Küsimused' },
  { index: 3, label: 'Testid' },
  { index: 4, label: 'Tulemused' },
]

export const SCHEMA_TABLES = [
  {
    name: 'role',
    group: 0,
    columns: [
      ['id', 'serial'],
      ['name', 'varchar(255)'],
    ],
  },
  {
    name: 'user',
    group: 0,
    columns: [
      ['id', 'serial'],
      ['email', 'varchar(255)'],
      ['password_hash', 'varchar(255)'],
      ['role_id', 'int'],
      ['status', 'char(1)'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'profile',
    group: 0,
    columns: [
      ['id', 'serial'],
      ['user_id', 'int'],
      ['first_name', 'varchar(255)'],
      ['last_name', 'varchar(255)'],
      ['phone_number', 'varchar(20)'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'invitation',
    group: 0,
    columns: [
      ['id', 'serial'],
      ['invited_by', 'int'],
      ['user_id', 'int'],
      ['token', 'varchar(255)'],
      ['created_at', 'timestamptz'],
      ['expires_at', 'timestamptz'],
      ['status', 'char(1)'],
    ],
  },
  {
    name: 'group',
    group: 0,
    columns: [
      ['id', 'serial'],
      ['name', 'varchar(255)'],
      ['status', 'char(1)'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'group_member',
    group: 0,
    columns: [
      ['id', 'serial'],
      ['group_id', 'int'],
      ['user_id', 'int'],
      ['added_by', 'int'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'group_manager',
    group: 0,
    columns: [
      ['id', 'serial'],
      ['group_id', 'int'],
      ['user_id', 'int'],
      ['status', 'char(1)'],
    ],
  },
  {
    name: 'level',
    group: 1,
    columns: [
      ['id', 'serial'],
      ['level', 'int'],
      ['name', 'varchar(255)'],
      ['description', 'varchar(255)'],
    ],
  },
  {
    name: 'competence',
    group: 1,
    columns: [
      ['id', 'serial'],
      ['name', 'varchar(255)'],
      ['short_description', 'varchar(255)'],
      ['description', 'text'],
      ['updated_at', 'timestamptz'],
      ['doc_url', 'varchar(500)'],
      ['doc_filename', 'varchar(255)'],
      ['status', 'char(1)'],
      ['created_by', 'int'],
      ['created_at', 'timestamptz'],
    ],
  },
  {
    name: 'competence_level',
    group: 1,
    columns: [
      ['id', 'serial'],
      ['competence_id', 'int'],
      ['level_id', 'int'],
      ['status', 'char(1)'],
    ],
  },
  {
    name: 'competence_file',
    group: 1,
    columns: [
      ['id', 'serial'],
      ['competence_id', 'int'],
      ['file_name', 'varchar(255)'],
      ['file_type', 'varchar(50)'],
      ['file_data', 'bytea'],
    ],
  },
  {
    name: 'question_type',
    group: 2,
    columns: [
      ['id', 'serial'],
      ['name', 'varchar(20)'],
    ],
  },
  {
    name: 'question',
    group: 2,
    columns: [
      ['id', 'serial'],
      ['competence_id', 'int'],
      ['competence_level_id', 'int'],
      ['title', 'varchar(100)'],
      ['description', 'varchar(1000)'],
      ['question_type_id', 'int'],
      ['score', 'int'],
      ['status', 'char(1)'],
      ['created_at', 'timestamptz'],
      ['created_by', 'int'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'question_answer',
    group: 2,
    columns: [
      ['id', 'serial'],
      ['question_id', 'int'],
      ['answer_text', 'varchar(255)'],
      ['correct_choice', 'boolean'],
      ['correct_position', 'int'],
      ['paired_answer_id', 'int'],
      ['status', 'char(1)'],
    ],
  },
  {
    name: 'ai_question',
    group: 2,
    columns: [
      ['id', 'serial'],
      ['title', 'varchar(100)'],
      ['description', 'varchar(1000)'],
      ['competence_id', 'int'],
      ['competence_level_id', 'int'],
      ['question_type_id', 'int'],
      ['status', 'char(1)'],
      ['created_at', 'timestamptz'],
      ['created_by', 'int'],
      ['updated_at', 'timestamptz'],
      ['score', 'int'],
      ['feedback', 'varchar(255)'],
      ['is_good', 'boolean'],
    ],
  },
  {
    name: 'ai_question_answer',
    group: 2,
    columns: [
      ['id', 'serial'],
      ['ai_question_id', 'int'],
      ['is_correct', 'boolean'],
      ['correct_position', 'int'],
      ['status', 'char(1)'],
      ['answer_text', 'varchar(255)'],
      ['ai_question_answer_id', 'int'],
      ['score', 'int'],
      ['feedback', 'int'],
    ],
  },
  {
    name: 'test',
    group: 3,
    columns: [
      ['id', 'serial'],
      ['competence_id', 'int'],
      ['competence_level_id', 'int'],
      ['name', 'varchar(255)'],
      ['short_description', 'varchar(150)'],
      ['description', 'text'],
      ['is_timed', 'boolean'],
      ['timer_min', 'int'],
      ['pass_percent', 'decimal(5,2)'],
      ['round_score_up', 'boolean'],
      ['status', 'char(1)'],
      ['created_by', 'int'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'test_question',
    group: 3,
    columns: [
      ['id', 'serial'],
      ['test_id', 'int'],
      ['question_id', 'int'],
      ['position', 'int'],
      ['added_by', 'int'],
      ['created_at', 'timestamptz'],
      ['updated_at', 'timestamptz'],
    ],
  },
  {
    name: 'user_test',
    group: 3,
    columns: [
      ['id', 'serial'],
      ['test_id', 'int'],
      ['user_id', 'int'],
      ['opens_at', 'timestamptz'],
      ['closes_at', 'timestamptz'],
      ['status', 'char(1)'],
      ['group_id', 'int'],
      ['assigned_by', 'int'],
      ['created_at', 'timestamptz'],
    ],
  },
  {
    name: 'result',
    group: 4,
    columns: [
      ['id', 'serial'],
      ['user_test_id', 'int'],
      ['status', 'char(1)'],
      ['max_score', 'int'],
      ['score_total', 'int'],
      ['completed_at', 'timestamptz'],
      ['started_at', 'timestamptz'],
      ['total_questions', 'int'],
      ['questions_answered', 'int'],
    ],
  },
  {
    name: 'test_question_result',
    group: 4,
    columns: [
      ['id', 'serial'],
      ['result_id', 'int'],
      ['question_id', 'int'],
      ['correct_answer', 'boolean'],
      ['status', 'varchar(2)'],
      ['sequence_number', 'int'],
    ],
  },
  {
    name: 'test_question_answer',
    group: 4,
    columns: [
      ['id', 'serial'],
      ['test_question_result_id', 'int'],
      ['question_answer_id', 'int'],
      ['correct_choice_user_answer', 'boolean'],
      ['correct_position_user_answer', 'int'],
      ['paired_answer_id_user_answer', 'int'],
    ],
  },
]

// Välisvõtmed: [tabel, veerg, viidatud tabel] — viidatakse alati viidatud tabeli id-le
export const SCHEMA_FOREIGN_KEYS = [
  ['user', 'role_id', 'role'],
  ['profile', 'user_id', 'user'],
  ['invitation', 'invited_by', 'user'],
  ['invitation', 'user_id', 'user'],
  ['group_member', 'group_id', 'group'],
  ['group_member', 'user_id', 'user'],
  ['group_member', 'added_by', 'user'],
  ['group_manager', 'group_id', 'group'],
  ['group_manager', 'user_id', 'user'],
  ['competence', 'created_by', 'user'],
  ['competence_level', 'competence_id', 'competence'],
  ['competence_level', 'level_id', 'level'],
  ['competence_file', 'competence_id', 'competence'],
  ['question', 'competence_id', 'competence'],
  ['question', 'competence_level_id', 'competence_level'],
  ['question', 'question_type_id', 'question_type'],
  ['question', 'created_by', 'user'],
  ['question_answer', 'question_id', 'question'],
  ['question_answer', 'paired_answer_id', 'question_answer'],
  ['ai_question', 'competence_id', 'competence'],
  ['ai_question', 'competence_level_id', 'competence_level'],
  ['ai_question_answer', 'ai_question_id', 'ai_question'],
  ['ai_question_answer', 'ai_question_answer_id', 'ai_question_answer'],
  ['test', 'competence_id', 'competence'],
  ['test', 'competence_level_id', 'competence_level'],
  ['test', 'created_by', 'user'],
  ['test_question', 'test_id', 'test'],
  ['test_question', 'question_id', 'question'],
  ['test_question', 'added_by', 'user'],
  ['user_test', 'test_id', 'test'],
  ['user_test', 'user_id', 'user'],
  ['user_test', 'group_id', 'group'],
  ['user_test', 'assigned_by', 'user'],
  ['result', 'user_test_id', 'user_test'],
  ['test_question_result', 'result_id', 'result'],
  ['test_question_result', 'question_id', 'question'],
  ['test_question_answer', 'test_question_result_id', 'test_question_result'],
  ['test_question_answer', 'question_answer_id', 'question_answer'],
  ['test_question_answer', 'paired_answer_id_user_answer', 'question_answer'],
]
